### ISSUE TITLE
I.B.4 AT for low vision

### ISSUE THREAD

**Issue by pkdash** [robfentress/cpacc-practice#36]
```

// Study task: I:B.4 Match disability categories with relevant assistive technologies

// Sources:
// The [Certified Professional in Accessibility Core Competencies Body of Knowledge](https://iaap.membershipsoftware.org/files/IAAP%20CPACC%20BOK%202017_062317.docx)

Which one of the following assistive technologies is useful for people who have low vision to access websites?
{
  ~Screen reading software
  ~Screen magnification software
  ~Software that enhances contrast
  = All of the above
}

```

**Comment by robfentress** [comment]
I made the following changes:

- I softened the question (changed "is" to "can be"); 
- removed "to access websites", since they can use these things to access their computer more generally and it reads better;
- fixed a formatting error (the space between the equals sign and the last answer option); and 
- changed "screen reading software" to "text-to-speech software," since you will usually hear "text-to-speech software" as the term used when the user has some sight.  "Screen reading software" usually suggests something like JAWS, which only fully blind people will use, generally.

Are those changes, incorporated below, okay?

```
// Study task: I:B.4 Match disability categories with relevant assistive technologies

// Sources:
// The [Certified Professional in Accessibility Core Competencies Body of Knowledge](https://iaap.membershipsoftware.org/files/IAAP%20CPACC%20BOK%202017_062317.docx)

Which one of the following assistive technologies can be useful for people who have low vision?
{
  ~Text-to-speech software
  ~Screen magnification software
  ~Software that enhances contrast
  =All of the above
}
```
